//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        public int id_i { get; set; }
        public string mobile_id { get; set; }
        public string name_nv { get; set; }
        public string color_nv { get; set; }
        public string size_nv { get; set; }
        public string camera_nv { get; set; }
        public string capacity_nv { get; set; }
        public string cdn_url { get; set; }
        public string description_nv { get; set; }
    }
}
