export const actionTypes = {
    HTTP_CALL_START: 'HTTP_CALL_START',
    HTTP_CALL_END: 'HTTP_CALL_END',
    HTTP_FINISH: 'HTTP_FINISH',
    VALIDATE_TOKEN: 'VALIDATE_TOKEN',
    GO_BACK: 'GO_BACK',
    CLEAR_STATE_FROM_PARENT: 'CLEAR_STATE_FROM_PARENT',
    ADD_TOKEN: 'ADD_TOKEN',
    CLEAR_STATE_FROM_AUTOCOMPLETE: 'CLEAR_STATE_FROM_AUTOCOMPLETE',
    CLEAR_STATE_FROM_SECOND_CHANCE: 'CLEAR_STATE_FROM_SECOND_CHANCE',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    SET_MODAL_NEXT_STEP: 'SET_MODAL_NEXT_STEP',
    LOAD_MOBILES_COMPLETED: 'LOAD_MOBILES_COMPLETED',
    TOGGLE_MODAL_MOBILE_DETAILS: 'TOGGLE_MODAL_MOBILE_DETAILS'
};
